name: sparse_sensing
channels:
  - pytorch
dependencies:
  - python=3.6
  - cudatoolkit=9.2
  - pip:
    - torch==1.5.1
    - torchvision==0.6.1
    - epic-kitchens==1.7.0
    - librosa
    - cupy-cuda92 
    - nose2
    - pyyaml
    - opencv-python
    - pandas
    - scikit-image
    - natsort
    - seaborn
    - tensorboard
    - tqdm
