batch_size: 48
num_workers: 36
n_epochs: 50
lr_steps: [20, 40]  # Epochs to decay learning rate by 10
print_freq: 20  # Print frequency
clip_gradient: 20.0  # Gradient norm clipping. Default = None
partialbn: True
freeze: False  # freeze all weights except fusion
eval_freq: 1
optimizer: 'SGD'
optim_params:
    lr: 0.001
    momentum: 0.9
    weight_decay: 1.e-4
