model_name: 'Pipeline3'
model_params:
    feat_model_cfg: 'configs/model_cfgs/san19_multi_pairwise_112_actnetpretrained.yaml'
    hallu_model_cfg: 'configs/model_cfgs/halluconvlstm2.yaml'
    num_class: 200
    num_segments: 16
    rnn_prefix_len: 5
    tf_decay: 0.95
    modality: ['RGB']
    attention_layer: ['layer3', '0']
    attention_dim: [32, 7, 7]
    new_length:
        RGB: 1
