model_name: 'PipelineSimple'
model_params:
    light_model_cfg: 'configs/model_cfgs/san19_multi_pairwise_112.yaml'
    heavy_model_cfg: 'configs/model_cfgs/id_model.yaml'
    time_sampler_cfg: 'configs/model_cfgs/id_time_sampler.yaml'
    space_sampler_cfg: 'configs/model_cfgs/id_space_sampler.yaml'
    actreg_model_cfg: 'configs/model_cfgs/fusion_classification_network_cat.yaml'
    using_cupy: False
    num_class: 200
    num_segments: 16
    modality: ['RGB']
    dropout: 0.5
    midfusion: 'concat'
    consensus_type: 'avg'
    new_length:
        RGB: 1
