model_name: 'ActregGRU3'
model_params:
    rnn_hidden_size: 1024
    rnn_num_layers: 2
    consensus_type: 'avg'
    weight_global: 0.4
    weight_local: 0.4
    weight_both: 0.2
    pretrained_global: ~
    pretrained_local: ~
    pretrained_both: 'pretrained/finetuned/actreggru2_top1_cat__nofc1_1024hid_2lay/actreg.model'
