model_name: 'PipelineSimple'
model_params:
    light_model_cfg: 'configs/model_cfgs/san19_multi_pairwise_64.yaml'
    heavy_model_cfg: 'configs/model_cfgs/id_model.yaml'
    time_sampler_cfg: 'configs/model_cfgs/id_time_sampler.yaml'
    space_sampler_cfg: 'configs/model_cfgs/id_space_sampler.yaml'
    actreg_model_cfg: 'configs/model_cfgs/fusion_classification_network_cat.yaml'
    num_class: [125, 352]
    num_segments: 3
    modality: ['RGBDS', 'Spec']
    dropout: 0.5
    midfusion: 'concat'
    consensus_type: 'avg'
    new_length:
        RGBDS: 1
        Spec: 1
