model_name: 'Pipeline5'
model_params:
    low_feat_model_cfg: 'configs/model_cfgs/san19_multi_pairwise_64_epicpretrained.yaml'
    high_feat_model_cfg: 'configs/model_cfgs/san19_multi_pairwise_epicpretrained.yaml'
    spatial_sampler_cfg: 'configs/model_cfgs/spatial_sampler_thres_top2.yaml'
    actreg_model_cfg: 'configs/model_cfgs/actreggru2.yaml'
    using_cupy: False
    num_class: [125, 352]
    num_segments: 10
    feat_process_type: 'cat'
    modality: ['RGB', 'Spec']
    attention_layer: ['layer2', '3']
    attention_dim: [16, 8, 8]
    dropout: 0.5
    new_length:
        RGB: 1
        Spec: 1
