model_name: 'Pipeline'
model_params:
    light_model_cfg: 'configs/model_cfgs/san19_multi_pairwise_epicpretrained.yaml'
    heavy_model_cfg: 'configs/model_cfgs/id_model.yaml'
    time_sampler_cfg: 'configs/model_cfgs/id_time_sampler.yaml'
    space_sampler_cfg: 'configs/model_cfgs/id_space_sampler.yaml'
    actreg_model_cfg: 'configs/model_cfgs/gru_convhallu2.yaml'
    num_class: [125, 352]
    num_segments: 3
    modality: ['RGB', 'Spec']
    dropout: 0.5
    attention_layer: ['layer3', '0']
    attention_dim: [32, 14, 14]
    hallu_loss: 'ssim'
    new_length:
        RGB: 1
        Spec: 1
