model_name: 'Pipeline8'
model_params:
    low_feat_model_cfg:   'configs/model_cfgs/san19_multi_pairwise_112_epicpretrained.yaml'
    high_feat_model_cfg:  'configs/model_cfgs/san19_multi_pairwise_epicpretrained.yaml'
    hallu_model_cfg:      'configs/model_cfgs/halluconvlstm2.yaml'
    actreg_model_cfg:     'configs/model_cfgs/actreggru2.yaml'
    spatial_sampler_cfg:  'configs/model_cfgs/spatial_sampler_thres_top3.yaml'
    temporal_sampler_cfg: 'configs/model_cfgs/temporal_sampler_rnn.yaml'
    hallu_pretrained_weights:  'pretrained/finetuned/halluconvlstm2_112_layer3-0/hallu.model'
    actreg_pretrained_weights: 'pretrained/finetuned/actreggru2_top3_cat__nofc1_1024hid_2lay/actreg.model'
    freeze_hallu: True
    freeze_actreg: False
    using_cupy: False
    temperature: 5.0
    temperature_exp_decay_factor: -0.045
    eff_loss_weights: 0.1
    num_class: [125, 352]
    num_segments: 10
    feat_process_type: 'cat'
    modality: ['RGB', 'Spec']
    attention_layer: ['layer3', '0']
    attention_dim: [32, 7, 7]
    dropout: 0.5
    new_length:
        RGB: 1
        Spec: 1
