model_name: 'Pipeline4'
model_params:
    feat_model_cfg: 'configs/model_cfgs/san19_multi_pairwise_64_epicpretrained.yaml'
    actreg_model_cfg: 'configs/model_cfgs/actreggru2.yaml'
    num_class: [125, 352]
    num_segments: 10
    modality: ['RGB', 'Spec']
    dropout: 0.5
    new_length:
        RGB: 1
        Spec: 1
