model_name: 'Pipeline'
model_params:
    light_model_cfg: 'configs/model_cfgs/san10_multi_pairwise.yaml'
    heavy_model_cfg: 'configs/model_cfgs/id_model.yaml'
    time_sampler_cfg: 'configs/model_cfgs/id_time_sampler.yaml'
    space_sampler_cfg: 'configs/model_cfgs/id_space_sampler.yaml'
    actreg_model_cfg: 'configs/model_cfgs/gru_hallu.yaml'
    num_class: [125, 352]
    num_segments: 3
    modality: ['RGB', 'Spec']
    dropout: 0.5
    attention_layer: ['layer4', '0']
    attention_dim: [64, 7, 7]
    new_length:
        RGB: 1
        Spec: 1
