model_name: 'SANMulti'
model_params:
    san_sa_type: 0  # Pairwise
    san_layers:  [3, 3, 4, 6, 3]
    san_kernels: [3, 7, 7, 7, 7]
    san_pretrained_weights: 
        RGB: 'pretrained/san19_epic_otherscales/112/rgb.model'
        Spec: 'pretrained/san19_epic_otherscales/112/spec.model'
    new_input_size: 112
    new_crop_size: 128
