model_name: 'SANMulti'
model_params:
    san_sa_type: 0  # Pairwise
    san_layers:  [2, 1, 2, 4, 1]
    san_kernels: [3, 7, 7, 7, 7]
    san_pretrained_weights: 'pretrained/san_imagenet/san10_pairwise/model/model_best.pth'
    new_input_size: 112
    new_crop_size: 128
