model_name: 'SANMulti'
model_params:
    san_sa_type: 1  # Patchwise
    san_layers:  [2, 1, 2, 4, 1]
    san_kernels: [3, 7, 7, 7, 7]
    san_pretrained_weights: 'pretrained/san_imagenet/san10_patchwise/model/model_best.pth'
