batch_size: 48
num_workers: 16
n_epochs: 50
lr_steps: [20, 40]  # Epochs to decay learning rate by 10
print_freq: 20  # Print frequency
clip_gradient: 20.0  # Gradient norm clipping. Default = None
partialbn: True
freeze: True  # freeze the feature extraction model
eval_freq: 1
optimizer: 'Adam'
optim_params:
    lr: 1.e-4
