dataset_name: 'epic_kitchens'
dataset_params:
    list_file:
        train: ~
        val:   ~
        test:  ~
    visual_path: 'data/EPIC_KITCHENS_2018/frames_restruct'
    audio_path: 'data/EPIC_KITCHENS_2018/audio_dict.pkl'
    use_audio_dict: True
    image_tmpl:
        RGB: 'img_{:010d}.jpg'
        Flow: '{}_{:010d}.jpg'
    depth_path: 'data/EPIC_KITCHENS_2018/depth'
    depth_tmpl: '0/PnPf/Inliers_{:04d}.txt'
    semantic_path: 'data/EPIC_KITCHENS_2018/semantic'
    semantic_tmpl: 'semantic_{}.data'
    resampling_rate: 24000
    fps: 60
    to_shuffle: False
